/usr/local/sbin/startdocker: line 3: /tmp/startdocker.log: Permission denied
/usr/local/sbin/startdocker: line 74: /tmp/startdocker.log: Permission denied
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/home/docker-root/overlay2/l/FXQBY2DA2EM42CZRFCWQZ4JZRZ:/home/docker-root/overlay2/l/EOHMOE5D4DQG6KEOP6D4WWZCXY:/home/docker-root/overlay2/l/OXKSGQO5DNCVA3QB3MCCJBYYRJ:/home/docker-root/overlay2/l/SQ5XXYHMYLAPFZ7HIRBTGZHCVH:/home/docker-root/overlay2/l/WH3B7D4LRNGVSPWZOT65N3RQE2:/home/docker-root/overlay2/l/BFTZ5HRE2XW22MCSX24CQL5RJ6:/home/docker-root/overlay2/l/PMW2ODDC2YNIQVMCFQQHGPG4OD:/home/docker-root/overlay2/l/AEINNPTYSUWX7E4NQKI5HQ7HBZ:/home/docker-root/overla'
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1168: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])) is deprecated. Please ensure they have the same size.
  "Please ensure they have the same size.".format(target.size(), input.size()))
Traceback (most recent call last):
  File "/gdata/huangzp/dsl_sgen/main.py", line 41, in <module>
    main(config)
  File "/gdata/huangzp/dsl_sgen/main.py", line 33, in main
    trainer.train()
  File "/gdata/huangzp/dsl_sgen/trainer.py", line 255, in train
    x_A_1, x_B_1 = A_loader.next(), B_loader.next()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 210, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 94, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "/usr/local/lib/python3.6/dist-packages/torch/storage.py", line 113, in _new_shared
    return cls._new_using_fd(size)
RuntimeError: unable to open shared memory object </torch_61_513207993> in read-write mode at /pytorch/torch/lib/TH/THAllocator.c:278

/usr/local/sbin/startdocker: line 3: /tmp/startdocker.log: Permission denied
/usr/local/sbin/startdocker: line 74: /tmp/startdocker.log: Permission denied
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/home/docker-root/overlay2/l/SUE5QETNKMWRHZRWY7GZABH6EJ:/home/docker-root/overlay2/l/EOHMOE5D4DQG6KEOP6D4WWZCXY:/home/docker-root/overlay2/l/OXKSGQO5DNCVA3QB3MCCJBYYRJ:/home/docker-root/overlay2/l/SQ5XXYHMYLAPFZ7HIRBTGZHCVH:/home/docker-root/overlay2/l/WH3B7D4LRNGVSPWZOT65N3RQE2:/home/docker-root/overlay2/l/BFTZ5HRE2XW22MCSX24CQL5RJ6:/home/docker-root/overlay2/l/PMW2ODDC2YNIQVMCFQQHGPG4OD:/home/docker-root/overlay2/l/AEINNPTYSUWX7E4NQKI5HQ7HBZ:/home/docker-root/overla'
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1168: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])) is deprecated. Please ensure they have the same size.
  "Please ensure they have the same size.".format(target.size(), input.size()))
